### ISSUE TITLE
Doesn't work as expected

### ISSUE THREAD

**Issue by smfreegard** [haraka/haraka-dsn#16]
Hey,

It's been a while since I worked on Haraka and I've just gone to improve an old plugin to use this module, however it does not appear to work as expected.

`return next(DENY, DSN.addr_bad_dest_system('This domain is not in use and does not accept mail', 550));`

Results in this being sent to the client:

`lr="550 [object Object] (C07121DB-B41C-42B1-9181-1CC8DA827628.1)"`

I'll try and look more at this tomorrow, but I wanted to log an issue so I don't forget...

**Comment by msimerson** [comment]
Why hello Steve! Nice to see you. :-)
