### ISSUE TITLE
dupe functionality

### ISSUE THREAD

**Issue by celesteking** [haraka/haraka-dsn#6]
Either abandon this plugin or incorporate https://github.com/haraka/Haraka/blob/master/dsn.js changes into this one and deprecate that one.

**Comment by celesteking** [comment]
but did you incorporate changes for that file? it doesn't look like.

**Comment by msimerson** [comment]
>  it doesn't look like.

a. I think so. If you don't, be more specific. 
b. it doesn't matter: everything is *already* using the packaged version.

**Comment by celesteking** [comment]
yeah, commit 4fd78e6 nailed it
